### PR TITLE
Configuration for clang-format

### PR DESCRIPTION
**Pull request by elliottslaughter**
Add clang-format configuration and run it. Contains only cosmetic changes (aside from `.clang-format` and `format.sh`).

### CODE REVIEW

**Comment by blackhole12** [comment]
I don't know what the state of this PR is, but I would greatly appreciate having a clang-format file, because Visual Studio can detect these, which would make it easier to edit code files without having to fight my own default formatting options or try to reverse-engineer what the project is doing.

**Comment by elliottslaughter** [comment]
I think my last push should have unbroken the build. The only issue at this point is that this commit needs to be done in coordination with the other outstanding branches so that we don't lose all our outstanding PRs when we do this. (I do *not* want to deal with the merge conflicts.)

Good news is I figured out how to do this with `git filter-branch`. Bad news is it's still has a fair number of manual steps and needs to be done with care or else we can lose the outstanding work.

**Comment by blackhole12** [comment]
Given that I still have three or so more planned PRs, I would like to get this in sooner rather than later. Can you detail the manual steps needed to make this happen so I can either split the work with you or do it myself?

**Comment by elliottslaughter** [comment]
I'll try to get to this today, and if I can't finish I'll follow up with instructions on how to do it.

Making for myself the list of branches that need to be kept up to date:

 *  StanfordLegion:puc_lua_master (aka  #320)
 * aiverson:master (aka #347) -- Note requires rebase onto master first
 *  ProfFan:llvm-8 (aka #408)
 * StanfordLegion:luajit2.1

If anyone else has outstanding branches that touch C/C++ files, let me know **now** or you will have substantial merge conflicts in the near future.

**Comment by elliottslaughter** [comment]
Ok, updated branches pushed here:

  * https://github.com/elliottslaughter/terra/tree/puc_lua_master
  * https://github.com/elliottslaughter/terra/tree/pr-347-rebase
  * https://github.com/elliottslaughter/terra/tree/llvm-8
  * https://github.com/elliottslaughter/terra/tree/luajit2.1

**Comment by ProfFan** [comment]
I took a look at this, looks fine for me, can rebase after this is merged

**Comment by elliottslaughter** [comment]
I did it over again because apparently clang-format is not compatible between releases. I am declaring that clang-format 9.0 is the official version for Terra, at least for the time being. There will be a subsequent update that will enforce that.

**Comment by elliottslaughter** [comment]
Ok, merged.

**Comment by elliottslaughter** [comment]
I updated all the original branches except for aiverson:master, which I'm guessing really wants to be a separate branch anyway. @aiverson you may need to do to this yourself. Other than that we should be good.

**Pull request merged**
