### PR TITLE
Add support for CMake-based build system

### PR DESCRIPTION
**Pull request by elliottslaughter**
This pull request adds a new build system based on CMake. The main advantage of CMake is that since LLVM has switched over to it, those libraries can now be found automatically. The old Makefile-based build system used a number of ugly workarounds to do the same thing, leading to bugs like [this one](https://github.com/zdevito/terra/issues/295) that are essentially impossible to fix in the existing infrastructure.

I have no plans to remove the Makefile based build, but going forward I suggest that CMake will be much easier to maintain and should be the focus of our efforts.

Currently this PR is mainly here to make sure the build gets tested. There are a number of missing features that will need to be added before this is ready for all the use cases currently supported by the existing Makefile.

Caveats:

  * Requires LLVM >= 3.6. It does not matter if LLVM was built with autoconf or CMake because the autoconf build also spits out the files CMake needs to find everything.
  * [DONE] Currently this only works on Linux. Will test macOS next.
  * [DONE] Not yet tested with CUDA.
  * Definitely not compatible with Windows. This may be an eventual goal but will require more work.

Other things I'd like to do at some point if I can find the time:

  * [DONE] Make the build fully out-of-tree. Right now there are a bunch of hacks that basically need it to be built in a very specific way. But changing this will require changing the test infrastructure too.
  * [DONE] Support for a proper installation option. The current one is kind of hack that only copies files into the `release` directory.

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Soliciting feedback from any potentially interested parties. Comments welcome.

@OvermindDL1 @Clyybber @manopapad @lightsighter (and anyone else with an interest in this)

**Comment by Clyybber** [comment]
This is great, much more cleaner than the Makefile.

**Comment by OvermindDL1** [comment]
I'd might also recommend using [hunter.sh](https://docs.hunter.sh/) or so to pull [LLVM](https://docs.hunter.sh/en/latest/packages/pkg/LLVM.html) directly.  This way you can specify the precise version you want terra to use with the precise build options and all.  Hunter.sh itself is just a 'HunterGate.cmake' file you include in the project and you specify a 'package repository listing' (like linked above via LLVM is the generic 'standard' one, but it is trivial to make up your own as a git repo or file download or so), it then compiles it with the options needed in a global area for re-use (overrideable of course) and exposes it into the application for full normal Modern CMake target linking.  This makes the builds entirely and fully reproducible and lowers the barrier of entry and usage (and people using wrong LLVM versions) without requiring any other dependencies (I.E. since Hunter.sh is a fully cmake dependency manager it will work with any setup and any build system without requiring anything but cmake itself to be installed).

And yes, CPack should definitely be used to build installers (Windows, sh, deb, etc... etc...).

**Comment by elliottslaughter** [comment]
Oh boy, is LLVM ever a mess. It seems like nearly every configuration that I don't compile myself is broken in one way or other.

Ubuntu 16.04:
  * LLVM 3.8 from source: compiles and passes all tests.
  * LLVM 3.8 from Ubuntu package repo: broken because the packagers decided to rename `/usr/share/llvm` to /usr/share/llvm-3.8` and forgot to update all the paths to point to the new location.
  * LLVM 3.8 from llvm.org binaries: broken with link errors due to what looks like a mismatch in C++11 symbols, but the usual tricks (`-fabi-version=2 -D_GLIBCXX_USE_CXX11_ABI=0`) don't fix it.
  * LLVM 3.8 from apt.llvm.org packages for Ubuntu: I somehow got my machine into a state where I can't install these, but I believe they compiled but segfault when running.

Ubuntu 14.04:
  * LLVM 3.8 from source: compiles and passes all tests.
  * LLVM 3.8 from Ubuntu package repo: broken, as above.
  * LLVM 3.8 from llvm.org binaries: compiles, but then segfaults when running.
  * LLVM 3.8 from apt.llvm.org packages for Ubuntu: compiles, but then segfaults when running.

Ouch.

I looked into Hunter a bit, and I like the basic idea (and especially how it's mostly invisible to end users), though I'm a bit concerned that as with any small-ish packaging system, the size of the community is going to be problematic. (This is my biggest reason for using Homebrew over MacPorts on macOS: packages are just that much more likely to be up-to-date and maintained when there are that many more people using the system.) However, practically speaking, the biggest issue is that they currently only seem to support [LLVM 3.6 and 4.0](https://github.com/hunter-packages/llvm), and the way packages are managed seems to involve unpacking the entire source tree into a Git repo and then modified by hand (!?!) so it's not super friendly to people doing it themselves.

**Comment by OvermindDL1** [comment]
> though I'm a bit concerned that as with any small-ish packaging system, the size of the community is going to be problematic. 

Huntergate is just the manager for it all.  The 'repository' used as an example by docs does have a lot of packages, however it is designed not to be centralized, you can fork it, can make your own from scratch, can use multiple repositories all at once, etc...  It was designed to be able to persist without any central location, which goes well with its 'invisible to the end user' aspect.

However I do not see it failing in any way, it has a clear set of goals and it is managed by one of the big cmake developers so it would not be unexpected to see huntergate be distributed with cmake itself one day as well considering how comparatively simple it is.

> Oh boy, is LLVM ever a mess. It seems like nearly every configuration that I don't compile myself is broken in one way or other.

But yes, this right here is why I will *not* touch LLVM from a package repository.  LLVM was not even designed to be used from a package repository as such considering how much of it is supposed to be configured at its own build time, and that's even before considering that they always seem to be highly out of date...

**Comment by elliottslaughter** [comment]
@OvermindDL1 Would you be willing to look into getting LLVM 3.8 included in the hunter.sh packages repo? Then I could at least play around with it.

For what it's worth, I think my CMake bug is not an instance of #235. The 14.04/16.04 packages are still definitely broken, but at least for 18.04 and built from source with CMake it should be possible to get CMake working.... I just have to figure out what's still different between the two builds.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Would you be willing to look into getting LLVM 3.8 included in the hunter.sh packages repo? Then I could at least play around with it.

Yeah it looks like no one has needed 3.8 so it was never added:
https://github.com/ruslo/hunter/blob/7f0c446acaf17d1ab91c8150cf3065947d91db15/cmake/projects/LLVM/hunter.cmake
It currently has:  3.4.2 3.5.0 3.6.0 3.6.2 3.6.2-p0 4.0.1-p0

They are generally quite open about PR's and/or requests, I'll go ahead and submit a request for both 3.8 as well as the latest 5.x and the in-dev 6.x.

Feature request submitted:  https://github.com/ruslo/hunter/issues/1522

**Comment by fabiencastan** [comment]
Is there still a plan to integrate a cmake build system in terra?

**Comment by elliottslaughter** [comment]
Yes, this is still the plan, I just haven't had time to get back to it yet.

**Comment by elliottslaughter** [comment]
Ok, the CMake build is now passing tests locally, so at this point I think it's just a matter of making Travis happy again.

The one thing I'm unhappy about at this point is that I couldn't get the tests to pass without extracting all the `.o` files from the static libraries and linking them in individually. I honestly don't understand how this is any different than `-Wl,--whole-archive`, but I can't get the tests to pass that way, so I guess we're stuck with this for now. It does mean that we rely on `CMAKE_AR` being set, so I'm not sure this will be portable.

One option would be to add a flag to specify dynamic linking, but you'd never get all the tests to pass under such a configuration.

**Comment by elliottslaughter** [comment]
I'm taking this pull request since all the basic features work, and there are systems where you basically can't build without it. Mac/Linux have been reasonable well-tested, including with CUDA. I'm leaving Windows and Hunter support to be revisited in the future. I've done some initial work to try to avoid making this platform-specific, but there will certainly be more to do when I try to go for full Windows support.

I'd still appreciate testing from anyone in this thread who is interested in CMake support. You can get it directly from master now that the PR has merged.

**Pull request merged**
