### PR TITLE
Update develop branch

### PR DESCRIPTION
**Pull request by Clyybber**
Side question: Should future pull request made to develop or master?

### CODE REVIEW

**Comment by elliottslaughter** [comment]
What is this pull request about?

My understanding, though @zdevito should correct me if I've got this wrong, is that we were planning on cherry-picking anything important from develop into master, and leaving the rest. (There were concerns with whether the current `develop` changes would be fully backwards compatible or not.) So any new work that you want to see merged should also target master.

**Comment by elliottslaughter** [comment]
Sorry, I see now this is doing `master -> develop` not `develop -> master`. That answers my first question. I think the rest of my previous comment still stands.

**Comment by elliottslaughter** [comment]
I should add: if there are specific changes in develop that you care about, please identify those and we can work on cherry-picking them into master.

**Comment by Clyybber** [comment]
Ok, should this still be merged? I guess it's easier to maintain if develop has the same base as master.

**Comment by Clyybber** [comment]
ping @elliottslaughter

**Comment by elliottslaughter** [comment]
My inclination would be to make this a rebase, and to specifically exclude anything that has already moved into master (i.e. Travis support). That way the set of commits on develop should shrink over time and it's obvious what is still outstanding (which can become hard to see when you merge). I'm guessing no one actually uses develop directly, so if we mess with history that's hopefully not a problem.

**Comment by Clyybber** [comment]
As @elliottslaughter said a rebase would be more appropriate.

**Pull request closed without merging**
