### PR TITLE
Fix order of Terra redirects causing output not to get captured on stderr

### PR DESCRIPTION
**Pull request by elliottslaughter**
Potential fix for #295.

### CODE REVIEW

**Comment by lightsighter** [comment]
No the patch still doesn't fix it. I checked out a fresh copy of terra and manually applied the patch before trying to build. I still see all the file names getting dumped to the screen instead of going into the llvm_list file. The problem should be with the Makefile rule on line 210 which builds 'llvm_list'.

**Comment by elliottslaughter** [comment]
@lightsighter Can you reclone and try again with the latest patch?

**Comment by elliottslaughter** [comment]
A simple test that confirms that the relative ordering of `2>&1` matters:

```
$ cat test_stderr.sh 
echo stdout
echo stderr 1>&2
$ chmod +x test_stderr.sh
$ ./test_stderr.sh > /dev/null
stderr
$ ./test_stderr.sh 2> /dev/null
stdout
$ ./test_stderr.sh 2>&1 > /dev/null
stderr
$ ./test_stderr.sh > /dev/null 2>&1
```

**Comment by elliottslaughter** [comment]
@lightsighter Confirmed the fix, taking this patch.

**Pull request merged**
