### PR TITLE
Update getting-started to match readme

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
Except for bin/terra -> ./terra and share/terra/tests -> tests as per [#126](https://github.com/zdevito/terra/issues/126)

### CODE REVIEW

**Comment by zdevito** [comment]
I think in this case the getting-started guide is more up-to-date than the readme, so the patch should probably go in the other direction except for the typos that were fixed in the readme.

**Comment by 0joshuaolson1** [comment]
I'll try again.

**Comment by 0joshuaolson1** [comment]
Too fast! I didn't get to say that [#186](https://github.com/zdevito/terra/pull/186) is only half of this - I'll fix this PR too.

**Comment by 0joshuaolson1** [comment]
I fixed 'download the download the' and added the first section that was only in getting started.

**Comment by 0joshuaolson1** [comment]
This is ready now.

**Pull request closed without merging**
