### PR TITLE
Compile functions when calling `printstats`

### PR DESCRIPTION
**Pull request by DarkWiiPlayer**
fix for #396

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Looks good, will merge after CI passes.

**Comment by elliottslaughter** [comment]
I am confused, but this actually seems to be causing a test failure on macOS with LLVM 3.8. I've rerun this job 4 times, and it seems to be deterministic. I also ran a dummy PR on master (#398) to confirm it doesn't show up there. I'm not sure what's going on though because as far as I can tell the failing test (`leaktest.t`) does not even call `printstats`.

**Comment by DarkWiiPlayer** [comment]
Well, I wish I could help with that, but if you say the test doesn't even directly call `printstats`, I highly doubt I'd be of any help figuring out what's causing the problem :\

**Comment by elliottslaughter** [comment]
I'm just going to merge this since `grep` isn't reporting any actual callsites for `printstats`. Perhaps there's an issue with the size of `terralib.lua` or something (since it gets included in the binary as a string), but aside from those sorts of second-order effects I can't think of what would be going on.

If the test keeps failing, I'll just turn it off; LLVM 3.8 isn't a high priority on macOS anyway.

**Pull request merged**
